/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ModulesModuleRouteImport } from './routes/modules/$module'
import { Route as WorkspaceModuleRouteImport } from './routes/workspace/$module'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ModulesModuleRoute = ModulesModuleRouteImport.update({
  id: '/modules/$module',
  path: '/modules/$module',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceModuleRoute = WorkspaceModuleRouteImport.update({
  id: '/workspace/$module',
  path: '/workspace/$module',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/modules/$module': typeof ModulesModuleRoute
  '/workspace/$module': typeof WorkspaceModuleRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/modules/$module': typeof ModulesModuleRoute
  '/workspace/$module': typeof WorkspaceModuleRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/modules/$module': typeof ModulesModuleRoute
  '/workspace/$module': typeof WorkspaceModuleRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/modules/$module' | '/workspace/$module'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/modules/$module' | '/workspace/$module'
  id: '__root__' | '/' | '/modules/$module' | '/workspace/$module'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ModulesModuleRoute: typeof ModulesModuleRoute
  WorkspaceModuleRoute: typeof WorkspaceModuleRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/modules/$module': {
      id: '/modules/$module'
      path: '/modules/$module'
      fullPath: '/modules/$module'
      preLoaderRoute: typeof ModulesModuleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workspace/$module': {
      id: '/workspace/$module'
      path: '/workspace/$module'
      fullPath: '/workspace/$module'
      preLoaderRoute: typeof WorkspaceModuleRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ModulesModuleRoute: ModulesModuleRoute,
  WorkspaceModuleRoute: WorkspaceModuleRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
